/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f2f4f7',
        'on-primary-container': '#fefcff',
        'outline-variant': '#c0c7d6',
        'on-background': '#191c1e',
        'error-container': '#ffdad6',
        'primary-container': '#0075d5',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#e0e3e6',
        'primary': '#005daa',
        'outline': '#707785',
        'surface-container-high': '#e6e8eb',
        'surface-container': '#eceef1',
        'secondary-container': '#8e4fee',
        'on-error': '#ffffff',
        'background': '#f7f9fc',
        'surface': '#f7f9fc',
        'error': '#ba1a1a',
        'inverse-surface': '#2d3133',
        'on-surface': '#191c1e',
        'on-primary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#404753',
        'surface-variant': '#e0e3e6',
        'secondary': '#7431d3',
        'on-primary-fixed-variant': '#004785',
        'primary-fixed': '#d4e3ff',
        'surface-bright': '#f7f9fc',
      },
      fontFamily: {
        headline: ['Inter', 'Noto Sans TC', 'sans-serif'],
        body: ['Inter', 'Noto Sans TC', 'sans-serif'],
        label: ['Inter', 'Noto Sans TC', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
